// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using deila.backend.Contexts;

#nullable disable

namespace deila.backend.Migrations
{
    [DbContext(typeof(DeilaDbContext))]
    [Migration("20220801230359_import-articles")]
    partial class importarticles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("deila.backend.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BasisId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Sentiment")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("deila.backend.Entities.Basis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Incidents")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Basiss");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Gender",
                            Incidents = 0
                        },
                        new
                        {
                            Id = 2,
                            Category = "Race",
                            Incidents = 0
                        },
                        new
                        {
                            Id = 3,
                            Category = "Disability",
                            Incidents = 0
                        },
                        new
                        {
                            Id = 4,
                            Category = "Other",
                            Incidents = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
